
--USERS table is created to store the details of all the users
DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE IF NOT EXISTS USERS(
    ID SERIAL PRIMARY KEY,
    UUID VARCHAR(200) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    USERNAME VARCHAR(30) UNIQUE NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL ,
    PASSWORD VARCHAR(255) NOT NULL,
    SALT VARCHAR(200) NOT NULL,
    COUNTRY VARCHAR(30),
    CONTACT_NUMBER VARCHAR(30)
);


INSERT INTO USERS(ID, UUID, FIRST_NAME, LAST_NAME, USERNAME, EMAIL, PASSWORD, SALT, COUNTRY, CONTACT_NUMBER)
	VALUES (101,'qwertyui','Saloni','Goyal','saloni','abc@gmail.com','507FF5FED1CAC746','8Xt6jxoCI3MWsVaKY/1ySAp2qzlb2Z7P89+vDrb1o6U=', 'India', '1222333333' );


--USER_AUTH table is created to store the login information of all the users
DROP TABLE IF EXISTS USER_AUTH CASCADE;
CREATE TABLE IF NOT EXISTS USER_AUTH(
	ID BIGSERIAL PRIMARY KEY,
	UUID VARCHAR(200) NOT NULL,
	USER_ID INTEGER NOT NULL,
	ACCESS_TOKEN VARCHAR(500) NOT NULL,
	EXPIRES_AT TIMESTAMP NOT NULL,
	LOGIN_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LOGOUT_AT TIMESTAMP NULL
);

ALTER TABLE USER_AUTH ADD CONSTRAINT FK_USER_AUTH_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ;
